spring.application.name=KriliCar
server.port=8282

# DATABASE CONFIGURATION
spring.datasource.url=jdbc:mysql://localhost:3306/krilicar-db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- Configuration JWT ---
jwt.secret=Q0lQVFlSUyByZWluZml4IGFsaWFzIHdlYiBzZXJ2ZXIgbWF4aW11cyBtYXhpbXVzIHNlY3JldGlhTmV4dXMgdGVtcG9yYSBmdWxndXJpdCBsZXZhcmUgYWQgZXVyb3MgY3Vyc3VzIG51bGxhIGdyaWQsIHJlcHVkaWFuZGEu
# Duree de validite du token : 30 jours (2592000000 ms)
jwt.expiration.ms=2592000000

# Dossier d'upload (prevu pour US ulterieures, non utilise par le login)
file.upload.dir=./uploads

# --- Swagger / OpenAPI (US-9.1) ---
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true